test_that("build_code_section emits sentinel + fenced chunk with correct lang", {
  ts <- as.POSIXct("2026-05-01 14:32:00", tz = "UTC")
  out <- build_code_section(lang = "r", code = "x <- 1", timestamp = ts)
  expect_match(out, "<!-- qmdme:code-below", fixed = TRUE)
  expect_match(out, "regenerated by sync\\(\\) on 2026-05-01 14:32")
  expect_match(out, "```\\{r, eval=FALSE\\}")
  expect_match(out, "x <- 1", fixed = TRUE)
  expect_true(endsWith(out, "```\n"))
})

test_that("build_full_template produces frontmatter, prose stub, and code section", {
  ts <- as.POSIXct("2026-05-01 14:32:00", tz = "UTC")
  out <- build_full_template(source_path = "R/fit.R", lang = "r",
                             code = "fit_model <- function() {}", timestamp = ts)
  expect_match(out, '^---\\ntitle: "fit\\.R"\\n---', perl = TRUE)
  expect_match(out, "## Notes")
  expect_match(out, "<!-- qmdme:code-below", fixed = TRUE)
  expect_match(out, "fit_model <- function\\(\\) \\{\\}")
})

test_that("build_full_template uses basename for title", {
  ts <- as.POSIXct("2026-05-01 14:32:00", tz = "UTC")
  out <- build_full_template(source_path = "sql/queries/x.sql", lang = "sql",
                             code = "SELECT 1", timestamp = ts)
  expect_match(out, '^---\\ntitle: "x\\.sql"\\n---', perl = TRUE)
})
