test_that("build_code_section emits sentinel + fenced chunk with correct lang", {
  out <- build_code_section(lang = "r", code = "x <- 1")
  expect_match(out, "<!-- qmdme:code-below", fixed = TRUE)
  expect_match(out, "regenerated by sync\\(\\)")
  expect_match(out, "```\\{r, eval=FALSE\\}")
  expect_match(out, "x <- 1", fixed = TRUE)
  expect_true(endsWith(out, "```\n"))
})

test_that("build_code_section sentinel carries no timestamp", {
  out <- build_code_section(lang = "r", code = "x <- 1")
  sentinel_line <- strsplit(out, "\n", fixed = TRUE)[[1]][1]
  # No 4-digit year, no HH:MM time-of-day pattern.
  expect_false(grepl("\\b\\d{4}\\b", sentinel_line))
  expect_false(grepl("\\b\\d{2}:\\d{2}\\b", sentinel_line))
})

test_that("build_code_section uses longer fence when code contains backticks", {
  code <- "x <- 1\n```\nsneaky\n```"
  out <- build_code_section(lang = "r", code = code)
  # Outer fence must be longer than the longest inner run (3) -> at least 4.
  expect_match(out, "````\\{r, eval=FALSE\\}", perl = TRUE)
  # And the matching closer is also four backticks.
  expect_true(grepl("\n````\n$", out, perl = TRUE))
})

test_that("chunk_fence uses the minimum 3 backticks when code has none", {
  expect_equal(chunk_fence("x <- 1\ny <- 2"), "```")
})

test_that("chunk_fence escalates past a 4-backtick run in the source", {
  # A source line with four backticks would close a 4-backtick outer fence, so
  # the fence must grow to five. (The 3->4 case is covered via sync in
  # test-sync.R and build_code_section above.)
  expect_equal(chunk_fence("a\n````\nb"), "`````")
})

test_that("build_full_template produces frontmatter, prose stub, and code section", {
  out <- build_full_template(source_path = "R/fit.R", lang = "r",
                             code = "fit_model <- function() {}")
  expect_match(out, '^---\\ntitle: "fit\\.R"\\n---', perl = TRUE)
  expect_match(out, "## Notes")
  expect_match(out, "<!-- qmdme:code-below", fixed = TRUE)
  expect_match(out, "fit_model <- function\\(\\) \\{\\}")
})

test_that("build_full_template uses basename for title", {
  out <- build_full_template(source_path = "sql/queries/x.sql", lang = "sql",
                             code = "SELECT 1")
  expect_match(out, '^---\\ntitle: "x\\.sql"\\n---', perl = TRUE)
})

test_that("build_full_template escapes double-quotes in the YAML title", {
  out <- build_full_template(source_path = 'odd"name.R', lang = "r",
                             code = "x <- 1")
  # Expect literal backslash-quote in the YAML title field.
  expect_match(out, 'title: "odd\\\\"name\\.R"', perl = TRUE)
})
