test_that("merge_with_sentinel preserves prose above sentinel", {
  existing <- paste0(
    "---\ntitle: \"fit.R\"\n---\n\n",
    "## Notes\n\n",
    "These are my notes. They explain the file.\n\n",
    "<!-- qmdme:code-below — do not edit below this line; ",
    "regenerated by sync() on 2026-04-01 10:00 -->\n\n",
    "```{r, eval=FALSE}\nold_code <- 1\n```\n"
  )
  new_section <- "<!-- qmdme:code-below new -->\n\n```{r, eval=FALSE}\nnew_code <- 2\n```\n"

  out <- merge_with_sentinel(existing, new_section)
  expect_match(out, "These are my notes. They explain the file.", fixed = TRUE)
  expect_match(out, "new_code <- 2", fixed = TRUE)
  expect_false(grepl("old_code", out, fixed = TRUE))
})

test_that("merge_with_sentinel returns NULL when no sentinel present", {
  existing <- "---\ntitle: \"fit.R\"\n---\n\n## My hand-written notes\n\nNo sentinel here.\n"
  new_section <- "<!-- qmdme:code-below new -->\n```{r}\n```\n"
  expect_null(merge_with_sentinel(existing, new_section))
})

test_that("merge_with_sentinel handles sentinel as first line", {
  existing <- "<!-- qmdme:code-below old -->\n```{r}\nold\n```\n"
  new_section <- "<!-- qmdme:code-below new -->\n```{r}\nnew\n```\n"
  out <- merge_with_sentinel(existing, new_section)
  expect_match(out, "new", fixed = TRUE)
  expect_false(grepl("old", out, fixed = TRUE))
})
