test_that("merge_with_sentinel preserves prose above sentinel", {
  existing <- paste0(
    "---\ntitle: \"fit.R\"\n---\n\n",
    "## Notes\n\n",
    "These are my notes. They explain the file.\n\n",
    "<!-- qmdme:code-below — do not edit below this line; ",
    "regenerated by sync() on 2026-04-01 10:00 -->\n\n",
    "```{r, eval=FALSE}\nold_code <- 1\n```\n"
  )
  new_section <- "<!-- qmdme:code-below new -->\n\n```{r, eval=FALSE}\nnew_code <- 2\n```\n"

  out <- merge_with_sentinel(existing, new_section)
  expect_match(out, "These are my notes. They explain the file.", fixed = TRUE)
  expect_match(out, "new_code <- 2", fixed = TRUE)
  expect_false(grepl("old_code", out, fixed = TRUE))
})

test_that("merge_with_sentinel appends new section when sentinel is missing", {
  existing <- "---\ntitle: \"fit.R\"\n---\n\n## Notes\n\nUser prose, no sentinel."
  new_section <- "<!-- qmdme:code-below new -->\n\n```{r, eval=FALSE}\nx <- 1\n```\n"
  out <- merge_with_sentinel(existing, new_section)
  expect_match(out, "User prose, no sentinel.", fixed = TRUE)
  expect_match(out, "<!-- qmdme:code-below new -->", fixed = TRUE)
  expect_match(out, "x <- 1", fixed = TRUE)
  # Original prose stays before the appended section.
  expect_lt(regexpr("User prose", out, fixed = TRUE),
            regexpr("qmdme:code-below", out, fixed = TRUE))
})

test_that("merge_with_sentinel handles empty existing content", {
  new_section <- "<!-- qmdme:code-below new -->\n\n```{r, eval=FALSE}\nx <- 1\n```\n"
  expect_equal(merge_with_sentinel("", new_section), new_section)
})

test_that("merge_with_sentinel handles sentinel as first line", {
  existing <- "<!-- qmdme:code-below old -->\n```{r}\nold\n```\n"
  new_section <- "<!-- qmdme:code-below new -->\n```{r}\nnew\n```\n"
  out <- merge_with_sentinel(existing, new_section)
  expect_match(out, "new", fixed = TRUE)
  expect_false(grepl("old", out, fixed = TRUE))
})
