# Website-scaffold templates for `init(scope = "website")`. These produce a
# self-contained, navigable Quarto website rooted at `qmd/` (its own
# `_quarto.yml`, rendering to `qmd/_site`), so the synced companions become
# pages of a site that renders on its own without touching any root
# `_quarto.yml`. See R/init.R.

#' Files written by `init()` for a given scope
#'
#' Returns a named list mapping a path relative to `qmd/` to the file's
#' contents (a character vector of lines). `init()` writes each entry
#' non-destructively. `embed` yields just the index stub (historical
#' behavior); `website` adds `_quarto.yml` and an `about.qmd` starter page.
#'
#' @param scope One of `"embed"` or `"website"`.
#' @return Named list of `relative-path -> character vector of lines`.
#' @keywords internal
init_files <- function(scope) {
  if (scope == "website") {
    list(
      "_quarto.yml" = build_site_quarto_yml(),
      "index.qmd"   = build_site_index(),
      "about.qmd"   = build_site_about()
    )
  } else {
    list("index.qmd" = build_embed_index())
  }
}

#' Embed-mode landing page (historical `init()` index stub)
#' @keywords internal
build_embed_index <- function() {
  c("---", 'title: "Code companions"', "---", "",
    "Code companions for the source files in this project.",
    "Each `.qmd` mirrors a source file with the original code in an",
    "`eval=FALSE` chunk.")
}

#' Website-mode `_quarto.yml`: a standalone website rooted at `qmd/`
#'
#' `project: type: website` renders to `qmd/_site`. A navbar links the Home and
#' About pages; an auto sidebar lists every companion `sync()` writes, so the
#' navigation stays current without manual edits.
#' @keywords internal
build_site_quarto_yml <- function() {
  c(
    "project:",
    "  type: website",
    "  output-dir: _site",
    "",
    "website:",
    '  title: "Code companions"',
    "  navbar:",
    "    left:",
    "      - href: index.qmd",
    "        text: Home",
    "      - href: about.qmd",
    "        text: About",
    "  sidebar:",
    "    style: floating",
    "    contents: auto",
    "",
    "# Companions display source verbatim; nothing here is ever executed, so",
    "# disable execution site-wide (no language kernel is started on render).",
    "execute:",
    "  enabled: false",
    "",
    "format:",
    "  html:",
    "    theme: cosmo",
    "    toc: true"
  )
}

#' Website-mode landing page
#' @keywords internal
build_site_index <- function() {
  c(
    "---",
    'title: "Code companions"',
    "---",
    "",
    "Welcome. These pages are **code companions** for the source files in",
    "this project: each one mirrors a source file, showing its code verbatim",
    "in an `eval=FALSE` chunk above any notes the authors have added.",
    "",
    "Use the sidebar to browse the companions. New ones appear automatically",
    "as `qmdme::sync()` is re-run.",
    "",
    "See [About](about.qmd) for how these pages are generated."
  )
}

#' Website-mode About starter page
#' @keywords internal
build_site_about <- function() {
  c(
    "---",
    'title: "About"',
    "---",
    "",
    "This site is generated by [qmdme](https://github.com/jessebrandtdata/qmdme).",
    "",
    "`qmdme::sync()` writes one Quarto companion per source file (`.R`,",
    "`.sql`, `.py`, ...). The code is shown, never executed. Everything above",
    "the `qmdme:code-below` marker in each page is hand-authored prose that",
    "`sync()` preserves; everything below it is regenerated from the source.",
    "",
    "To rebuild this site after syncing, run `quarto render` in the `qmd/`",
    "directory."
  )
}
