SENTINEL_PREFIX <- "<!-- qmdme:code-below"

#' Format a timestamp for the sentinel line
#' @keywords internal
format_ts <- function(ts) {
  format(ts, "%Y-%m-%d %H:%M", tz = "UTC")
}

#' Build the auto-generated section: sentinel line + fenced eval=FALSE chunk
#'
#' @param lang Quarto chunk-language tag (e.g. "r", "sql", "python").
#' @param code Source code string, included verbatim in the chunk.
#' @param timestamp POSIXct used for the sentinel.
#' @return Character scalar.
#' @keywords internal
build_code_section <- function(lang, code, timestamp = Sys.time()) {
  paste0(
    SENTINEL_PREFIX, " — do not edit below this line; ",
    "regenerated by sync() on ", format_ts(timestamp), " -->\n\n",
    "```{", lang, ", eval=FALSE}\n",
    code,
    if (!grepl("\n$", code)) "\n" else "",
    "```\n"
  )
}

#' Build the full qmd template for a new companion file
#'
#' @param source_path Source file path (used for the title).
#' @param lang Quarto chunk-language tag.
#' @param code Source-code body.
#' @param timestamp POSIXct for the sentinel.
#' @return Character scalar — the full file contents.
#' @keywords internal
build_full_template <- function(source_path, lang, code,
                                timestamp = Sys.time()) {
  paste0(
    "---\n",
    'title: "', basename(source_path), '"\n',
    "---\n\n",
    "## Notes\n\n",
    "<!-- everything above the marker is yours; sync() never touches it -->\n\n",
    build_code_section(lang, code, timestamp)
  )
}
