# Detection downstream uses `startsWith(line, SENTINEL_PREFIX)`. Changing this
# string breaks every existing companion file in every project -- treat as a
# stable contract. See also R/merge.R, R/sync.R.
SENTINEL_PREFIX <- "<!-- qmdme:code-below"

#' Pick a fenced-code-block delimiter long enough to wrap `code`
#'
#' Returns a run of at least three backticks, and at least one more than the
#' longest run of backticks appearing in `code`. This prevents source files
#' whose contents contain triple-backtick fences from closing the outer chunk
#' prematurely.
#'
#' @param code Source code string.
#' @return Character scalar, a run of backticks.
#' @keywords internal
chunk_fence <- function(code) {
  runs <- regmatches(code, gregexpr("`+", code))[[1]]
  longest <- if (length(runs) == 0) 0L else max(nchar(runs))
  strrep("`", max(3L, longest + 1L))
}

#' Build the auto-generated section: sentinel line + fenced eval=FALSE chunk
#'
#' @param lang Quarto chunk-language tag (e.g. "r", "sql", "python").
#' @param code Source code string, included verbatim in the chunk.
#' @return Character scalar.
#' @keywords internal
build_code_section <- function(lang, code) {
  fence <- chunk_fence(code)
  paste0(
    SENTINEL_PREFIX, " \u2014 do not edit below this line; ",
    "regenerated by sync() -->\n\n",
    fence, "{", lang, ", eval=FALSE}\n",
    code,
    if (!grepl("\n$", code)) "\n" else "",
    fence, "\n"
  )
}

#' Build the full qmd template for a new companion file
#'
#' @param source_path Source file path (used for the title).
#' @param lang Quarto chunk-language tag.
#' @param code Source-code body.
#' @return Character scalar with the full file contents.
#' @keywords internal
build_full_template <- function(source_path, lang, code) {
  title <- gsub('"', '\\"', fs::path_file(source_path), fixed = TRUE)
  paste0(
    "---\n",
    'title: "', title, '"\n',
    "---\n\n",
    "## Notes\n\n",
    "<!-- everything above the marker is yours; sync() never touches it -->\n\n",
    build_code_section(lang, code)
  )
}
